# Generated by Django 2.2.4 on 2021-01-19 21:17

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        normalized_phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(normalized_phone_number):
            flat.owner_pure_phone = normalized_phone_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_flat_owner_pure_phone"),
    ]

    operations = [migrations.RunPython(normalize_phone_number)]
